### ISSUE TITLE
Sending a message the a User just before deleting it prevents the operation from happening

### ISSUE THREAD

**Issue by gretro** [tradle/bots#4]
Hello.

I need to delete a user under certain conditions. Since the Web App context is not deleted at the same time as the user, I would like to advise the user his profile has been destroyed and the bot no longer knows him. However, when I send the message, it holds a reference to the user until the message is effectively sent, then modifies the history to report that sent message and saves the user without returning a Promise for that whole process.

This means that it is impossible to wait for a message to be effectively sent before doing some other operation. In this case, it creates a race condition between my call to `bot.users.clear()` and the message being sent.

The bot API should either support sending a message immediately without it being queued or there should be a way to wait for the queue to be drained for a specific user.

Here is my code
```
const users = botApi.users.list();
const destroyMessagePromise = Object.keys(users).map(userId => {
  return send(userId, PROFILE_DESTROYED_MESSAGE);
});

return Promise.all(destroyMessagePromise)
  .then(() => {
    botApi.users.clear();
  })
  .catch(err => {
    console.error('Unable to destroy user profiles', err);
  });
```

**Comment by mvayngrib** [comment]
@gretro yes, this is because send enqueueing is decoupled from send execution. `bot.send()` really means something like "place this message in the persistent send queue". There's a trade-off: on the one hand, sends survive the process being restarted. On the other hand it prevents you from getting a Promise that resolves when the message is sent.

One way to work around this would be to build your Promise around the `"sent"` event. Here's a sketch:

```js
let destroy = {...}
bot.send({ userId, object: destroy })
return new Promise(resolve => {
  bot.on('sent', function ({ user, object }) {
    // check if it's the destroy message, e.g. against the object being sent, against the user's history
    // or in some custom way
    if (deepEqual(object, destroy)) {
       // unsubscribe and resolve
    }
  })
})
```

this obviously breaks if the process is terminated while waiting for the event, but it's probably ok to start with?

**Comment by gretro** [comment]
Ok, will try that out.

**Comment by gretro** [comment]
For anyone interested in the solution, here is what I did. It works with text messages.

```js
function send(userId, message) {
    return new Promise((resolve, reject) => {
      let resolved = false;
      const sentListener = function messageSentListener({ user, object }) {
        const isSameUser = user && user.id === userId;
        const isSameMessage = object && object.message === message;
        
        if (isSameUser && isSameMessage && !resolved) {
          resolved = true;
          botApi.removeListener('sent', sentListener);
          if (timeout) {
            clearTimeout(timeout);
          }

          resolve({ user, object });
        }
      };

      botApi.on('sent', sentListener);
      botApi.send({ userId, object: message });

      const timeout = setTimeout(() => {
        if (!resolved) {
          resolved = true;
          botApi.removeListener('sent', sentListener);
          reject('Watcher has timed out');
        }
      }, 10000);
    });
  }
```
